### ISSUE TITLE
Getting this now when I run a clean project

### ISSUE THREAD

**Issue by MDrooker** [cnnlabs/cnn-hapi#13]
Debug: internal, implementation, error 
    TypeError: Uncaught error: request.response.header is not a function
    at setCacheControlHeaders (/Users/matthewjon/Development/Projects/watercooler-api/node_modules/cnn-hapi/main.js:63:26)

  request.response.header('Surrogate-Control', surrogateControl);

**Comment by MDrooker** [comment]
Its because you need to check for isBoom...this fails if a 404 is being served

**Comment by adslaton** [comment]
0.5.1 released
